### ISSUE TITLE
There is an error when trying to access to Not Visible product

### ISSUE THREAD

**Issue by Serzhik** [CompactCodeEU/FixProductBreadcrumbs#4]
### How to reproduce:

- Disable product
- Try to go to the product's URL

**Comment by CompactCodeEU** [comment]
What is the error that you are getting?

**Comment by CompactCodeEU** [comment]
This module will be reviewed and reworked in the coming 2 weeks. I will put it in the notification

**Comment by givan808** [comment]
Same error.
I create and enable product - everything is OK. Then I disable/make invisible and try to follow the link - get this error:

Fatal error: Uncaught Error: Call to undefined method Magento\Framework\Controller\Result\Forward\Interceptor::getLayout() in /app/code/CompactCode/FixProductBreadcrumbs/Plugin/Product/View.php:62 Stack trace: #0 /vendor/magento/framework/Interception/Interceptor.php(146): CompactCode\FixProductBreadcrumbs\Plugin\Product\View->afterExecute(Object(Magento\Catalog\Controller\Product\View\Interceptor), Object(Magento\Framework\Controller\Result\Forward\Interceptor)) #1 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Product\View\Interceptor->Magento\Framework\Interception\{closure}() #2 /generated/code/Magento/Catalog/Controller/Product/View/Interceptor.php(26): Magento\Catalog\Controller\Product\View\Interceptor->___callPlugins('execute', Array, Array) #3 /vendor/magento/framework/App/Action/Action.php(107): Magento\Catalog\Controller\Product\View\Interceptor->execut in /app/code/CompactCode/FixProductBreadcrumbs/Plugin/Product/View.php on line 62
